version: '3.7'

services:
  web-client:
    build:
      context: ./client
      dockerfile: Dockerfile
#      args:
#        - CONFIGURATION=development
    container_name: web-client
    image: web-client
    ports:
      - "80:80"
    networks:
      - osbb-network

  postgres-osbb:
    image: postgres
    container_name: postgres-osbb
    command: postgres -c 'max_connections=50'
    volumes:
      - ./../../data/postgres/data:/var/lib/postgresql/data
      - ./../../data/postgres/backups:/opt/backups
    environment:
      - POSTGRES_DB=osbb
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432
    networks:
      - osbb-network

  mongo-osbb:
    image: mongo:4.2.3
    container_name: mongo-osbb
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=osbb-mongodb-admin
      - MONGO_INITDB_ROOT_PASSWORD=osbb-mongodb-admin-e6c165c87c03
      - AUTH_DB=admin
      - DB_USER=mongo-user
      - DB_PASS=mongo-pass
      - DB_NAME=osbb
    volumes:
      - ./data/mongo/:/data/db
      - ./databases/mongo-entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    networks:
      - osbb-network

  osbb-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: osbb-api:latest
    container_name: osbb-api
    environment:
      SPRING_PROFILES_ACTIVE: development
    networks:
      - osbb-network
    depends_on:
      - mongo-osbb
      - postgres-osbb
    ports:
      - 8082:8082
      - 1082:1082

  grafana:
    image: grafana/grafana:6.2.2
    ports:
      - 3000:3000
    volumes:
      - ./databases/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./databases/SystemDashboard.json:/var/lib/grafana/dashboards/SystemDashBoard.json
      - ./databases/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.7.6
    ports:
      - 8086:8086
    #    volumes:
    #      - /var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: boot
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret




networks:
  osbb-network:
    name: osbb-network
    driver: bridge
