server:
  port: 8081

spring:
  application:
    name: ossb

  data:
    mongodb:
      database: osbb
      username: mongo-user
      password: mongo-pass
      port: 27017
      host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/osbb
    driver-class-name: org.postgresql.Driver
    username: app_user
    password: 12345678
    hikari:
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
#  metrics:
#    export:
#      influx:
#        db: boot
#        userName: user
#        password: pass
#        uri: http://influxdb:8086
#        step: 15s
#        auto-create-db: false


