global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs
  - job_name: 'java_application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['osbb-api:8082']
#  - remote_read:
#      - url: "http://timescale-prometheus-connector:9201"
#  - remote_write:
#      - url: "http://timescale-prometheus-connector:9201"


